/**
 * DATA ALAMAT PERSONIL MDS LENGKAP 100% (75 MDS SE-INDONESIA)
 * Generated automatically from live Google Sheet Master_User
 */
const MDS_PERSONNEL_DATA = [
    {
        "id": "3.5623",
        "nama": "MUHAMMAD FEBRIMA NURSA",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "DK1",
        "alamat": "Jl. Flamboyan V RT 05/RW 10, Menteng Dalam",
        "kecamatan": "Tebet",
        "kota": "Jakarta Selatan",
        "region": "JABODETABEK",
        "lat": -6.224454,
        "lng": 106.849919
    },
    {
        "id": "3.6047",
        "nama": "ANDRIZKY SIMBOLON",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "DK1",
        "alamat": "Jl. Raya Ciruas, Kp. Pasar, RT 003/RW 001, Desa Nyapah",
        "kecamatan": "Karawaci",
        "kota": "Kota Tangerang",
        "region": "JABODETABEK",
        "lat": -6.195022,
        "lng": 106.615045
    },
    {
        "id": "3.6584",
        "nama": "ABDUL KHOLIK",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "DK1",
        "alamat": "Jl. Cibarengkok, RT 012/005, Desa Sukamulya",
        "kecamatan": "Cikupa",
        "kota": "Kabupaten Tangerang",
        "region": "JABODETABEK",
        "lat": -6.248784,
        "lng": 106.521732
    },
    {
        "id": "3.6786",
        "nama": "MARJUKI",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "DK1",
        "alamat": "Kp. Sumur Sawo RT 18/RW 06, Desa Citalahab",
        "kecamatan": "\u00e2\u20ac\u201d",
        "kota": "Kabupaten Pandeglang",
        "region": "JABODETABEK",
        "lat": -6.309795,
        "lng": 106.106418
    },
    {
        "id": "3.6902",
        "nama": "MIA ANJELINA",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "DK1",
        "alamat": "Jalan Nusa Indah No. 18, RT 13/RW 25",
        "kecamatan": "Bekasi Utara",
        "kota": "Kota Bekasi",
        "region": "JABODETABEK",
        "lat": -6.216397,
        "lng": 107.009801
    },
    {
        "id": "3.7379",
        "nama": "IRFANTO ABINOWO PAMBUKO",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "DK1",
        "alamat": "Jl. Gaga 1, RT 02/RW 09, No. 33, Kel. Gaga",
        "kecamatan": "Larangan",
        "kota": "Kota Tangerang",
        "region": "JABODETABEK",
        "lat": -6.231715,
        "lng": 106.73877
    },
    {
        "id": "NEW 1",
        "nama": "ANDI IRFANSYAH",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "DK1",
        "alamat": "Jl. Gg. H. Hasbi 5 No. 26, Kampung Bali",
        "kecamatan": "Tanah Abang",
        "kota": "Jakarta Pusat",
        "region": "JABODETABEK",
        "lat": -6.190053,
        "lng": 106.814272
    },
    {
        "id": "3.5064",
        "nama": "RISWANDI",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "DK2",
        "alamat": "Kp. Parungdengdek RT 03/RW 11, Desa Wanaherang",
        "kecamatan": "Gunung Putri",
        "kota": "Kabupaten Bogor",
        "region": "JABODETABEK",
        "lat": -6.442939,
        "lng": 106.920444
    },
    {
        "id": "3.5405",
        "nama": "ANGGA SETIAWAN",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "DK2",
        "alamat": "Jl. Anin Adjim RT 03/RW 01, Warujaya",
        "kecamatan": "Parung",
        "kota": "Kabupaten Bogor",
        "region": "JABODETABEK",
        "lat": -6.42772,
        "lng": 106.730805
    },
    {
        "id": "3.5569",
        "nama": "RIANSYAH RASYIDILHAMID",
        "jabatan": "Merchandiser",
        "account": "FAMILY MART",
        "modul": "DK2",
        "alamat": "Jl. Masjid At-Taqwa Gg. H. Mada No. 117, RT 03/RW 02, Kel. Kembangan Utara",
        "kecamatan": "Kembangan",
        "kota": "Jakarta Barat",
        "region": "JABODETABEK",
        "lat": -6.1685,
        "lng": 106.745022
    },
    {
        "id": "3.6056",
        "nama": "RINA ARIANA",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "DK2",
        "alamat": "Jln. Raya Cigintung, Kp. Kabul RT/RW 001/005, Kel. Gelam",
        "kecamatan": "Cipocok Jaya",
        "kota": "Kota Serang",
        "region": "JABODETABEK",
        "lat": -6.117683,
        "lng": 106.159219
    },
    {
        "id": "3.6413",
        "nama": "NANA SUTISNA",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "DK2",
        "alamat": "Kp. Karamat RT 03/RW 01, Kel. Panaragan",
        "kecamatan": "Bogor Tengah",
        "kota": "Kota Bogor",
        "region": "JABODETABEK",
        "lat": -6.592899,
        "lng": 106.799537
    },
    {
        "id": "3.6585",
        "nama": "NANANG JAZULI",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "DK2",
        "alamat": "Kp. Rawa Bacang, RT 001/RW 013, Kel. Jatirahayu",
        "kecamatan": "Pondok Melati",
        "kota": "Kota Bekasi",
        "region": "JABODETABEK",
        "lat": -6.310047,
        "lng": 106.925684
    },
    {
        "id": "3.7332",
        "nama": "MUHAMMAD IRFAN NURSAID",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "DK2",
        "alamat": "Jl. Al Baidho I Gg. Sadar IV RT 006/RW 006, Kel. Lubang Buaya",
        "kecamatan": "Cipayung",
        "kota": "Jakarta Timur",
        "region": "JABODETABEK",
        "lat": -6.196749,
        "lng": 106.816202
    },
    {
        "id": "3.7644",
        "nama": "MUHAMMAD FIKRI DARMAWAN",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "DK2",
        "alamat": "Jl. Kapten Yusuf, RT 04/RW 11, Desa Kota Batu",
        "kecamatan": "Ciomas",
        "kota": "Kabupaten Bogor",
        "region": "JABODETABEK",
        "lat": -6.60644,
        "lng": 106.760212
    },
    {
        "id": "3.4473",
        "nama": "TITI SRIYATI",
        "jabatan": "Merchandiser",
        "account": "ALFAMIDI",
        "modul": "DK3",
        "alamat": "Jl. Pengadegan Utara IV RT 006/RW 007, Kel. Pengadegan",
        "kecamatan": "Pancoran",
        "kota": "Jakarta Selatan",
        "region": "JABODETABEK",
        "lat": -6.259807,
        "lng": 106.843624
    },
    {
        "id": "3.4695",
        "nama": "SARIPUDIN",
        "jabatan": "Merchandiser",
        "account": "ALFAMIDI",
        "modul": "DK3",
        "alamat": "Perumahan Babelan Garden City, Jalan Kedung Pengawas Blok A19 No. 18, RT 01/RW 07, Desa/Kel. Kedungpengawas",
        "kecamatan": "Babelan",
        "kota": "Kabupaten Bekasi",
        "region": "JABODETABEK",
        "lat": -6.178755,
        "lng": 107.038302
    },
    {
        "id": "3.5427",
        "nama": "ZORO HARMOKO",
        "jabatan": "Merchandiser",
        "account": "ALFAMIDI",
        "modul": "DK3",
        "alamat": "Jl. Nami RT 008/RW 002, Kel. Cijantung",
        "kecamatan": "Pasar Rebo",
        "kota": "Jakarta Timur",
        "region": "JABODETABEK",
        "lat": -6.314251,
        "lng": 106.869944
    },
    {
        "id": "3.5986_DK3_19",
        "nama": "TAUFIK",
        "jabatan": "Merchandiser",
        "account": "FAMILY MART",
        "modul": "DK3",
        "alamat": "Jl. Batu Merah 1 RT 02/RW 02 No. 33, Pejaten Timur",
        "kecamatan": "Pasar Minggu",
        "kota": "Jakarta Selatan",
        "region": "JABODETABEK",
        "lat": -6.280435,
        "lng": 106.83704
    },
    {
        "id": "3.6488",
        "nama": "YANTO",
        "jabatan": "Merchandiser",
        "account": "ALFAMIDI",
        "modul": "DK3",
        "alamat": "Jl. Sempur Kadu RT 02/RW 06, Desa Kadu",
        "kecamatan": "Curug",
        "kota": "Kabupaten Tangerang",
        "region": "JABODETABEK",
        "lat": -6.260817,
        "lng": 106.562261
    },
    {
        "id": "3.6593",
        "nama": "ANDRE ADITIA MULYANA",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "DK3",
        "alamat": "Kp. Beji RT 01/RW 01, Desa Kosambi",
        "kecamatan": "Sukadiri",
        "kota": "Kabupaten Tangerang",
        "region": "JABODETABEK",
        "lat": -6.075044,
        "lng": 106.57
    },
    {
        "id": "3.7405",
        "nama": "RIZALDI",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "DK3",
        "alamat": "Kp. Sugu Tamu RT/RW 008/021 No. 110, Kel. Mekarjaya",
        "kecamatan": "Sukmajaya",
        "kota": "Kota Depok",
        "region": "JABODETABEK",
        "lat": -6.409231,
        "lng": 106.842336
    },
    {
        "id": "3.7405",
        "nama": "RIZALDI PRASETYO BUDI",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK4",
        "alamat": "Kp. Sugu Tamu RT/RW 008/021 No. 110, Kel. Mekarjaya",
        "kecamatan": "Sukmajaya",
        "kota": "Kota Depok",
        "region": "JABODETABEK",
        "lat": -6.409528,
        "lng": 106.847121
    },
    {
        "id": "3.7466",
        "nama": "FAZAL KHAIRI MUFRI",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP1",
        "alamat": "Jl. Botania Garden",
        "kecamatan": "Batam Kota",
        "kota": "Kota Batam",
        "region": "LUAR PULAU",
        "lat": 1.134338,
        "lng": 104.059956
    },
    {
        "id": "3.5743",
        "nama": "SANDY SAPUTRA",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP3",
        "alamat": "Jl. Jend. Sudirman Palembang",
        "kecamatan": "Ilir Timur",
        "kota": "Kota Palembang",
        "region": "LUAR PULAU",
        "lat": -2.961187,
        "lng": 104.758235
    },
    {
        "id": "RO031",
        "nama": "RAHMAT AGIL",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP3",
        "alamat": "Jl. Kapten Pattimura",
        "kecamatan": "Alam Barajo",
        "kota": "Kota Jambi",
        "region": "LUAR PULAU",
        "lat": -1.610218,
        "lng": 103.613539
    },
    {
        "id": "3.7059",
        "nama": "THERESA LIANA RUSLI",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LP3",
        "alamat": "Jl. Padat Karya Sempaja, Gg. Karya Mandiri, RT 08, Kel. Sempaja Timur",
        "kecamatan": "Samarinda Utara",
        "kota": "Kota Samarinda",
        "region": "LUAR PULAU",
        "lat": -0.502106,
        "lng": 117.153709
    },
    {
        "id": "3.6277",
        "nama": "FARMADI SATRIA",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP1",
        "alamat": "Jl. H.R. Soebrantas Panam",
        "kecamatan": "Tampan",
        "kota": "Kota Pekanbaru",
        "region": "LUAR PULAU",
        "lat": 0.511682,
        "lng": 101.44126
    },
    {
        "id": "3.6867",
        "nama": "MARIE GALI",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP1",
        "alamat": "Jl. H.M. Yamin No. 120",
        "kecamatan": "Medan Perjuangan",
        "kota": "Kota Medan",
        "region": "LUAR PULAU",
        "lat": 3.58006,
        "lng": 98.675771
    },
    {
        "id": "RO044",
        "nama": "I KETUT PRADNYANA",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LP1",
        "alamat": "Jl. Bypass Tabanan",
        "kecamatan": "Tabanan",
        "kota": "Kabupaten Tabanan",
        "region": "LUAR PULAU",
        "lat": -8.54702,
        "lng": 115.129574
    },
    {
        "id": "3.6356",
        "nama": "MELKY PARYONO",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP2",
        "alamat": "Jl. Lintas Timur Unit 2",
        "kecamatan": "Banjar Margo",
        "kota": "Kabupaten Tulang Bawang",
        "region": "LUAR PULAU",
        "lat": -4.292243,
        "lng": 105.229171
    },
    {
        "id": "RO032",
        "nama": "ANGGI NOVRI ANDIKA",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP2",
        "alamat": "Jl. R.A. Basyid",
        "kecamatan": "Sukarame",
        "kota": "Kota Bandar Lampung",
        "region": "LUAR PULAU",
        "lat": -5.39,
        "lng": 105.284934
    },
    {
        "id": "RO033",
        "nama": "AHMAD GHOZALI",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP2",
        "alamat": "Jl. Jend. Sudirman Metro",
        "kecamatan": "Metro Barat",
        "kota": "Kota Metro",
        "region": "LUAR PULAU",
        "lat": -5.112355,
        "lng": 105.300757
    },
    {
        "id": "R153",
        "nama": "SULKAHFI",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP2",
        "alamat": "Jl. Sultan Alauddin",
        "kecamatan": "Rappocini",
        "kota": "Kota Makassar",
        "region": "LUAR PULAU",
        "lat": -5.167141,
        "lng": 119.430482
    },
    {
        "id": "12410bdc",
        "nama": "MUSTAPA KAMAL",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP4",
        "alamat": "Jl. Raya Waker Jonggat",
        "kecamatan": "Jonggat",
        "kota": "Kabupaten Lombok Tengah",
        "region": "LUAR PULAU",
        "lat": -8.709959,
        "lng": 116.27436
    },
    {
        "id": "RO037",
        "nama": "RAENALDI SH",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP4",
        "alamat": "Jl. Lestari Pejeruk Bangket, Gg. Manalagi 11 RT 003/RW 021, Kel. Pejeruk",
        "kecamatan": "Ampenan",
        "kota": "Kota Mataram",
        "region": "LUAR PULAU",
        "lat": -8.588218,
        "lng": 116.118827
    },
    {
        "id": "RO045",
        "nama": "NI KADEK NUTRIANI",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LP4",
        "alamat": "Jl. A. Yani Utara, Gg. Anugrah 6, Perumahan Nuansa Anugrah 6 Blok G No. 1",
        "kecamatan": "Denpasar Utara",
        "kota": "Kota Denpasar",
        "region": "LUAR PULAU",
        "lat": -8.653518,
        "lng": 115.219775
    },
    {
        "id": "3.6623",
        "nama": "BEDI SULISTIO",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP1",
        "alamat": "Jl. Raden Fatah Gg. Bemo No. 9, Kel. Kaliawi",
        "kecamatan": "Tanjung Karang Pusat",
        "kota": "Kota Bandar Lampung",
        "region": "LUAR PULAU",
        "lat": -5.420181,
        "lng": 105.266333
    },
    {
        "id": "3.5533",
        "nama": "ILHAM",
        "jabatan": "Merchandiser",
        "account": "",
        "modul": "LP4",
        "alamat": "Jl. Tanjung Harapan, Gg. Kejora 2, RT 02/RW 01, Banjar Serasan",
        "kecamatan": "Pontianak Timur",
        "kota": "Kota Pontianak",
        "region": "LUAR PULAU",
        "lat": -0.02633,
        "lng": 109.342504
    },
    {
        "id": "RO040",
        "nama": "SYAHRUL RAMADHAN",
        "jabatan": "",
        "account": "",
        "modul": "LP",
        "alamat": "Perumahan Taman Raya Tahap 4, Blok NK No. 03, RT 04/RW 18, Kel. Belian",
        "kecamatan": "Batam Kota",
        "kota": "Kota Batam",
        "region": "LUAR PULAU",
        "lat": 1.134207,
        "lng": 104.050063
    },
    {
        "id": "3.6613",
        "nama": "ARIFKI",
        "jabatan": "Merchandiser",
        "account": "",
        "modul": "LP4",
        "alamat": "Jl. Kadir TKR, Lorong Keluarga, RT 035/RW 005, Kel. 36 Ilir",
        "kecamatan": "Gandus",
        "kota": "Kota Palembang",
        "region": "LUAR PULAU",
        "lat": -2.989583,
        "lng": 104.753
    },
    {
        "id": "RO039",
        "nama": "MULWI MAHESA",
        "jabatan": "Merchandiser",
        "account": "",
        "modul": "LP4",
        "alamat": "Komplek Bintang Pesona, Jalan Perintis Baru, Kampung Lalang",
        "kecamatan": "Sunggal",
        "kota": "Kabupaten Deli Serdang / Kota Medan",
        "region": "LUAR PULAU",
        "lat": 3.580841,
        "lng": 98.677776
    },
    {
        "id": "3.7345",
        "nama": "ALDY KURNIAWAN",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LK1",
        "alamat": "Dusun Krajan, RT 001/RW 011, Desa Mojosari",
        "kecamatan": "Puger",
        "kota": "Kabupaten Jember",
        "region": "PULAU JAWA",
        "lat": -8.174911,
        "lng": 113.709999
    },
    {
        "id": "RO002",
        "nama": "ALFEIN BASRI RAMDHANI",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LK1",
        "alamat": "Jl. Pecilon Indah 5 No. 19, RT 002/RW 002, Kel. Sutawinangun",
        "kecamatan": "Kedawung",
        "kota": "Kabupaten Cirebon",
        "region": "PULAU JAWA",
        "lat": -6.710745,
        "lng": 108.537627
    },
    {
        "id": "RO003",
        "nama": "ALI BUDIONO",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK1",
        "alamat": "Papandayan Kp, Kalilangse RT 02 RW 05 NO. 363",
        "kecamatan": "Gajah Mungkur",
        "kota": "Semarang",
        "region": "PULAU JAWA",
        "lat": -7.010491,
        "lng": 110.402839
    },
    {
        "id": "RO004",
        "nama": "AMININ",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK1",
        "alamat": "Jl Kolonel sugino 2 . no 47 rt6 rw3 kel Ciptomulyo",
        "kecamatan": "Sukun",
        "kota": "Malang",
        "region": "PULAU JAWA",
        "lat": -7.994382,
        "lng": 112.610038
    },
    {
        "id": "RO005",
        "nama": "ANGGA DELA K",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK1",
        "alamat": "Karanggumul RT 01 RW 06 Kel. Kahuman",
        "kecamatan": "Polahharjo",
        "kota": "Kab. Klaten",
        "region": "PULAU JAWA",
        "lat": -7.708841,
        "lng": 110.601799
    },
    {
        "id": "3.7148",
        "nama": "KHOLIFAH MULYANI",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LK2",
        "alamat": "Jl. Babakan Jati Mulya V No. 54, RT 01/RW 07, Kel. Gumuruh",
        "kecamatan": "Batununggal",
        "kota": "Kota Bandung",
        "region": "PULAU JAWA",
        "lat": -6.919769,
        "lng": 107.606503
    },
    {
        "id": "RO007",
        "nama": "CATUR DARMAWAN",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK2",
        "alamat": "Jl. Sastro RT. 2 RW. 1, Ds. Kertobanyon",
        "kecamatan": "Geger",
        "kota": "Kab. Madiun",
        "region": "PULAU JAWA",
        "lat": -7.626312,
        "lng": 111.529825
    },
    {
        "id": "RO008",
        "nama": "DEDE SODIKIN",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK2",
        "alamat": "Jl cisereuh Rt 04 Rw 01 Kel karang tengah",
        "kecamatan": "Gunung Puyuh",
        "kota": "Sukabumi",
        "region": "PULAU JAWA",
        "lat": -6.921649,
        "lng": 106.938711
    },
    {
        "id": "RO009",
        "nama": "FELDY FIRMANSYAH AKBAR",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK2",
        "alamat": "blok pajawan RT 10 RW 03 desa talagawetan",
        "kecamatan": "Talaga",
        "kota": "Kan.majalengka",
        "region": "PULAU JAWA",
        "lat": -6.8361,
        "lng": 108.2274
    },
    {
        "id": "RO011",
        "nama": "HENDRAWAN",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK2",
        "alamat": "Kp. Rancabogo Rt/Rw 003/001 Tambakmekar",
        "kecamatan": "Jalancagak",
        "kota": "Subang",
        "region": "PULAU JAWA",
        "lat": -6.57158,
        "lng": 107.75873
    },
    {
        "id": "RO012",
        "nama": "IGNATIUS INDRA",
        "jabatan": "Merchandiser",
        "account": "LAWSON",
        "modul": "LK2",
        "alamat": "Krembung barat rt 21 rw 09",
        "kecamatan": "Krembung",
        "kota": "Sidoarjo",
        "region": "PULAU JAWA",
        "lat": -7.457794,
        "lng": 112.710853
    },
    {
        "id": "3.6997",
        "nama": "MIKA ADITYA",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LK3",
        "alamat": "Jengkol, Garung",
        "kecamatan": "Garung",
        "kota": "Kabupaten Wonosobo",
        "region": "PULAU JAWA",
        "lat": -7.369999,
        "lng": 109.905111
    },
    {
        "id": "RO014",
        "nama": "KRISNA",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK3",
        "alamat": "Caringin Babakan rt02/03",
        "kecamatan": "Ngamprah",
        "kota": "kab.bandung barat",
        "region": "PULAU JAWA",
        "lat": -6.917608,
        "lng": 107.609266
    },
    {
        "id": "RO015",
        "nama": "M REZA FIRDAUS",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK3",
        "alamat": "Bogem, Tamanmartani",
        "kecamatan": "Kalasan",
        "kota": "Kab. Sleman",
        "region": "PULAU JAWA",
        "lat": -7.71556,
        "lng": 110.35556
    },
    {
        "id": "RO016",
        "nama": "MAULANA ARIF HIDAYAT",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK3",
        "alamat": "Dsn. Pasanggrahan Rt. 04 Rw. 04 Ds. Cijambu",
        "kecamatan": "Tanjungsari",
        "kota": "Sumedang",
        "region": "PULAU JAWA",
        "lat": -6.8586,
        "lng": 107.9269
    },
    {
        "id": "RO018",
        "nama": "MOCH IAN MULYADI",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK3",
        "alamat": "kp.Babakan Situ Rt.003/008 Desa Cileunyi Wetan",
        "kecamatan": "Cileunyi",
        "kota": "Kab Bandung",
        "region": "PULAU JAWA",
        "lat": -6.911816,
        "lng": 107.601145
    },
    {
        "id": "RO019",
        "nama": "MUH TAUFIK HIDAYATULLAH",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK3",
        "alamat": "Jl. Kanguru selatan 9C No. 50",
        "kecamatan": "Gayamsari",
        "kota": "Semarang",
        "region": "PULAU JAWA",
        "lat": -6.996524,
        "lng": 110.420238
    },
    {
        "id": "RO020",
        "nama": "MUHAMAD HERMAWAN",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK4",
        "alamat": "Simpar 012/005 ds,simpar",
        "kecamatan": "cipunagara",
        "kota": "subang",
        "region": "PULAU JAWA",
        "lat": -6.568,
        "lng": 107.76
    },
    {
        "id": "RO021",
        "nama": "PUGUH",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK4",
        "alamat": "jl wonosari ds toyomarto dsn petung wulung RT 03 RW 06",
        "kecamatan": "Singosari",
        "kota": "Kab. Malang",
        "region": "PULAU JAWA",
        "lat": -7.988696,
        "lng": 112.638368
    },
    {
        "id": "RO022",
        "nama": "RISKI AHMAD TAUFIK",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK4",
        "alamat": "Jl raung dusun gudang karang",
        "kecamatan": "Rambipuji",
        "kota": "Jember",
        "region": "PULAU JAWA",
        "lat": -8.174163,
        "lng": 113.709929
    },
    {
        "id": "RO023",
        "nama": "RIZKY FIRMANSYAH",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK4",
        "alamat": "Jl. Gubeng Airlangga 2 no 21A",
        "kecamatan": "Gubeng",
        "kota": "Surabaya",
        "region": "PULAU JAWA",
        "lat": -7.2504,
        "lng": 112.756959
    },
    {
        "id": "RO024",
        "nama": "SETIAWAN BAYU",
        "jabatan": "Merchandiser",
        "account": "ALFAMIDI",
        "modul": "LK4",
        "alamat": "Rungkut lor 7/No-47-B",
        "kecamatan": "Rungkut",
        "kota": "Surabaya",
        "region": "PULAU JAWA",
        "lat": -7.250866,
        "lng": 112.752188
    },
    {
        "id": "3.6693",
        "nama": "THOMAS ARTINTA NANDO",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LK5",
        "alamat": "Kripik Gede RT 12/RW 004, Desa Malangan",
        "kecamatan": "Tulung",
        "kota": "Kabupaten Klaten",
        "region": "PULAU JAWA",
        "lat": -7.705133,
        "lng": 110.600002
    },
    {
        "id": "RO027",
        "nama": "VIKTOR HERO KASIM",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LK5",
        "alamat": "Jl. Arjuna No. 322, RT 23/RW 13",
        "kecamatan": "Tumpang",
        "kota": "Kabupaten Malang",
        "region": "PULAU JAWA",
        "lat": -7.989278,
        "lng": 112.632411
    },
    {
        "id": "RO028",
        "nama": "Wahyu Irgi Prastya Mu'thi",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LK5",
        "alamat": "Dsn. Sidorame, RT 09/RW 03, Ds. Sidorejo",
        "kecamatan": "Krian",
        "kota": "Kabupaten Sidoarjo",
        "region": "PULAU JAWA",
        "lat": -7.45949,
        "lng": 112.717201
    },
    {
        "id": "RO034",
        "nama": "MUHAMAD IRVIN",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LP3",
        "alamat": "Jl. Zam Zam Djailani, Guntung Luar, Kel. Kemuning",
        "kecamatan": "Banjarbaru Selatan",
        "kota": "Kota Banjarbaru",
        "region": "LUAR PULAU",
        "lat": -3.454122,
        "lng": 114.832459
    },
    {
        "id": "3.7149",
        "nama": "ROBY FAHRANA",
        "jabatan": "Merchandiser",
        "account": "INDOMARET",
        "modul": "LP3",
        "alamat": "Jl. Jaya Koncara 2 Tempuran 03, RT 008/RW 003, Dsn. Tempuran",
        "kecamatan": "Tempuran",
        "kota": "Kabupaten Karawang",
        "region": "PULAU JAWA",
        "lat": -6.305,
        "lng": 107.305
    },
    {
        "id": "RO017",
        "nama": "MOCH ANANG MULYONO",
        "jabatan": "Merchandiser",
        "account": "",
        "modul": "LK4",
        "alamat": "kp.Babakan Situ Rt.003/008 Desa Cileunyi Wetan",
        "kecamatan": "Cileunyi",
        "kota": "Kab Bandung",
        "region": "PULAU JAWA",
        "lat": -6.910245,
        "lng": 107.603455
    },
    {
        "id": "RO001",
        "nama": "ALDRIAN MAULANA",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK1",
        "alamat": "Jl. Raya Cibeber - Cilaku",
        "kecamatan": "Cilaku",
        "kota": "Kabupaten Cianjur",
        "region": "PULAU JAWA",
        "lat": -6.863731,
        "lng": 107.130164
    },
    {
        "id": "RO006",
        "nama": "BAYU BURHAN",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK1",
        "alamat": "Jl. Raya Kawunganten",
        "kecamatan": "Kawunganten",
        "kota": "Kabupaten Cilacap",
        "region": "PULAU JAWA",
        "lat": -7.588384,
        "lng": 108.911319
    },
    {
        "id": "RO010",
        "nama": "FUAD MUSTANGIN",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK2",
        "alamat": "Jl. Jend. Sudirman Kroya",
        "kecamatan": "Kroya",
        "kota": "Kabupaten Cilacap",
        "region": "PULAU JAWA",
        "lat": -7.729926,
        "lng": 109.015859
    },
    {
        "id": "RO025",
        "nama": "SUGIARTO",
        "jabatan": "Merchandiser",
        "account": "ALFAMART",
        "modul": "LK4",
        "alamat": "Jl. Raya Lebaksiu Slawi",
        "kecamatan": "Lebaksiu",
        "kota": "Kabupaten Tegal",
        "region": "PULAU JAWA",
        "lat": -7.046939,
        "lng": 109.149609
    }
];

if (typeof window !== "undefined") {
    window.MDS_PERSONNEL_DATA = MDS_PERSONNEL_DATA;
}
